### PR TITLE
update miniperl to 5.38.0

### PR DESCRIPTION
**Pull request by hadfl**

### CODE REVIEW

**Comment by richlowe** [comment]
This looks good.  I've run into other problems while building it that I need to figure out, and then I'll merge this.

Have you seen errors building binutils-gdb?  For reasons I don't understand it fails building sim now.  I'm going to just disable sim, but it seems weird that something changed and it doesn't seem to be something of ours.

**Comment by richlowe** [comment]
So I think this needs to include changes so that `perl` in the resulting image is 5.38 too?  Without that, intrd fails on boot (and I got weird failures from `dma` too, but those might not be related).

**Comment by hadfl** [comment]
> Have you seen errors building binutils-gdb? For reasons I don't understand it fails building sim now. I'm going to just disable sim, but it seems weird that something changed and it doesn't seem to be something of ours.

Yes, I hit the issue building with gcc 13, that's why I had opened a PR to fix it: https://github.com/richlowe/binutils-gdb/pull/1

**Comment by hadfl** [comment]
> So I think this needs to include changes so that `perl` in the resulting image is 5.38 too? Without that, intrd fails on boot (and I got weird failures from `dma` too, but those might not be related).

This is a follow-up PR from bumping perl to 5.38 in OmniOS. The problem is that you tested during the timespan before the PR for OmniOS has been approved and therefore no new packages have been published, yet to the repository.
Once it's there, intrd should work again. We could probably force it here to install perl@5.38, however that would break creating images completely until perl 5.38 is in the repository which I think will be a bigger impact than just intrd failing.

**Comment by richlowe** [comment]
Ok.  I'll give this another spin, and merge/send a heads-up about 5.38 if it works.  Thanks!

**Pull request merged**
