### PR TITLE
miniperl added for cross building illumos-gate perl modules

### PR DESCRIPTION
**Pull request by hadfl**

### CODE REVIEW

**Comment by richlowe** [comment]
This seems good.  I think you need something in build_disk to actually put it on the disk?  One of the downsides of not having packaging, and the sysroot containing bits in the way of the packaging we do have.

Do you have the bits for illumos to build the perl stuff, or is that still work in progress?

**Comment by richlowe** [comment]
I found the illumos-gate bits, the github email was being unhelpful.

**Comment by citrus-it** [comment]
Looks good to me - I built a disk image with this and the illumos PR commits and everything looked good.
FWIW, `intrd` is now running!

```
root@braich:~# uname -a
SunOS braich 5.11 arm64-gate-0-ga31a984857 armv8 aarch64 QEMU,virt-4.1
root@braich:~# svcs -p intrd
STATE          STIME    FMRI
online         11:40:19 svc:/system/intrd:default
               11:40:16   100826 intrd
```

**Comment by richlowe** [comment]
Integrated

**Pull request closed without merging**
